global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'config-manager'
    static_configs:
      - targets: ['config-manager:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'discord-bot'
    static_configs:
      - targets: ['discord-bot:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'planner-agent'
    static_configs:
      - targets: ['planner-agent:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'coder-agent'
    static_configs:
      - targets: ['coder-agent:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'reviewer-agent'
    static_configs:
      - targets: ['reviewer-agent:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 60s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s